#ifndef OPERATINGSYSTEMS_COMMANDS_H
#define OPERATINGSYSTEMS_COMMANDS_H

#define PROJECT_ID 0x098
#define MAX_PACKAGE_COUNT 10
#define WORKING_TIME 10
#define SEMAPHORES_SIZE 6
#define PACKAGES_TO_PREPARE "/PACKAGES_TO_PREPARE"
#define PACKAGES_TO_SEND "/PACKAGES_TO_SEND"
#define MEMORY_BUSY "/MEMORY_BUSY"
#define PACKAGE_TO_PREPARE_INDEX "/PACKAGE_TO_PREPARE_INDEX"
#define PACKAGE_TO_SEND_INDEX "/PACKAGE_TO_SEND_INDEX"
#define PACKAGE_TO_CREATE_INDEX "/PACKAGE_TO_CREATE_INDEX"
#define SHARED_MEMORY "/PACKAGE_TO_CREATE_INDEX"
#define rand_time ((rand() % (100 - 1000 + 1) + 100) * 1000)
const char* SEMAPHORES[SEMAPHORES_SIZE] = {PACKAGES_TO_PREPARE, PACKAGES_TO_SEND, MEMORY_BUSY, PACKAGE_TO_PREPARE_INDEX, PACKAGE_TO_SEND_INDEX, PACKAGE_TO_CREATE_INDEX};

#endif //OPERATINGSYSTEMS_COMMANDS_H
