#ifndef OPERATINGSYSTEMS_COMMANDS_H
#define OPERATINGSYSTEMS_COMMANDS_H

#define PROJECT_ID 0x098
#define PACKAGE_COUNT 10
#define WORKING_TIME 10
#define SEMAPHORE_SIZE 3
#define PACKAGES_TO_PREPARE 0
#define PACKAGES_TO_SEND 1
#define MEMORY_BUSY 2


#endif //OPERATINGSYSTEMS_COMMANDS_H
