#ifndef OPERATINGSYSTEMS_COMMANDS_H
#define OPERATINGSYSTEMS_COMMANDS_H

#define PROJECT_ID 0x098
#define MAX_PACKAGE_COUNT 10
#define WORKING_TIME 10
#define SEMAPHORE_SIZE 6
#define PACKAGES_TO_PREPARE 0
#define PACKAGES_TO_SEND 1
#define MEMORY_BUSY 2
#define PACKAGE_TO_PREPARE_INDEX 3
#define PACKAGE_TO_SEND_INDEX 4
#define PACKAGE_TO_CREATE_INDEX 5
#define rand_time ((rand() % (100 - 1000 + 1) + 100) * 1000)

#endif //OPERATINGSYSTEMS_COMMANDS_H
